version: "3.7"
services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/config/nginx/Dockerfile
    volumes:
      - ./docker/config/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - internal

  frontend:
    build:
      context: ./
      dockerfile: ./docker/config/frontend/Dockerfile
    depends_on:
      - nodejs
    volumes:
      - ./frontend:/usr/src/app/
      - ./docker/config/frontend/init.sh:/init.sh
    networks:
      - internal

  nodejs:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./docker/config/nodejs/Dockerfile
    volumes:
      - ./nodejs:/usr/src/app/
      - ./docker/config/nodejs/init.sh:/init.sh
    networks:
      - internal

  database:
    build:
      context: ./
      dockerfile: ./docker/config/database/Dockerfile
    volumes:
      - ./docker/data/database:/var/lib/mysql
      - ./docker/logs/database:/var/log/mysql
    ports:
      - '3306:3306'
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MAX_EXECUTION_TIME: 3600
      UPLOAD_LIMIT: 500M
    volumes:
      - ./docker/data/phpmyadmin/sessions:/sessions
    ports:
      - '8080:80'
    networks:
      - internal

networks:
  internal:
    driver: bridge